config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, :through => :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktails, only: %i[show edit destroy update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def edit; end

  def update
    @cocktail.update(cocktail_params)
    redirect_to @cocktail
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path(@cocktails)
  end

  private

  def set_cocktails
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredient, :doses, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: %i[new create]
  before_action :find_dose, only: [:destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
  end

  private

  def find_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/edit.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/941864/pexels-photo-941864.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div class="container">
    <h1>Welcome to the Anonymous Bar!</h1>
    <p>The best cocktails</p>
  </div>
</div>

<div class="container viewheight">

  <div class="d-flex justify-content-center">
  <%= link_to "<button class='btn-2'> Add a cocktail !</button>".html_safe, new_cocktail_path, :class => "button" %>
  </div>

  <div class="cards">
  <% @cocktails.each do |cocktail| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),url(https://source.unsplash.com/featured/?drinks,<%=cocktail.name%>);">

  <%= link_to cocktail.name, cocktail, :class => "decoration" %>
      </div>
  <% end %>
  </div>
</div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon Batch #296
  </div>

app/views/cocktails/new.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
  <div class="navbar">

    <div class="border"><%= link_to "Back to cocktails", cocktails_path, :class => "links" %></div>
    <div class="border"><%= link_to "Edit", edit_cocktail_path(@cocktail), :class => "links" %></div>
    <div class="border"><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), :class => "links" %></div>
    <div class="border"><%= link_to "Delete", cocktail_path(@cocktail), :class => "links", method: "delete",
          data: { confirm: "Are you sure?" } %></div>
  </div>

<div class="text-center">
  <div class=drinks_infos>
    <div>
      <h1><%= @cocktail.name %></h1>
      <% @cocktail.doses.each do |dose| %>
      <%= dose.ingredient.name %>
      <%= dose.description %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1>Add Ingredient to <%= @cocktail.name %></h1>
      <%= simple_form_for [@cocktail, @cocktail.ingredient] do |f| %>

        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class: 'select2' }, include_hidden: false  %>

        <%= f.submit 'Add Ingredient', class: 'btn btn-primary' %>

      <% end %>

    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>